### ISSUE TITLE
同一行解析两次

### ISSUE THREAD

**Issue by trygittog** [fanfeilong/exceltk#3]
你好，我使用wps的excel（后缀xlsx），复制带有多行的表格后，同一行会解析两次，不知道是不是小程序出的问题还是我电脑剪切板的问题？

**Comment by fanfeilong** [comment]
wps的还没测过，找个时间看下，目前如果你被解析了两次，你可以收工删一下。

**Comment by trygittog** [comment]
恩，我目前也是这样做的虽然多行会有些麻烦。还是谢谢你的小工具啦

**Comment by fanfeilong** [comment]
能否提供一个样本文件供测试用，我这边没有wps
