### ISSUE TITLE
excel xls <br/> can NOT parse in one table cell

### ISSUE THREAD

**Issue by tmc9031** [fanfeilong/exceltk#7]
if in xls use "Enter", hope output markdown

|ID|xx|
|:--|:--|
|1<br/>1|2|
|2|3|

but tool output

|ID|xx|
|:--|:--|
|1\<br/\>|1|2|
|2|3|

**Comment by fanfeilong** [comment]
The <br/> HTML label is inserted,  and the output is a valid markdown table.
After the markdown be rendered, the `newline` in the cell will be kept.

You can try it in the stackeditor.io , see the flowing picture.

![table](https://user-images.githubusercontent.com/2046098/32653215-010352bc-c642-11e7-90be-fbbe1636b411.png)

**Comment by tmc9031** [comment]
ok，i found problem is in table cell already exist "|"
then lead to table parse more rank 

so whether add new feature to transfer "|" to "\\|" in excel table cell

**Comment by fanfeilong** [comment]
That's really a bug,  👍 
I will fix it. 💤

**Comment by fanfeilong** [comment]
the bug is fixed, see the 0.1.3 version.
