### ISSUE TITLE
Linux支持

### ISSUE THREAD

**Issue by neosun100** [fanfeilong/exceltk#9]
Great app！能否在Linux下编译为可执行文件，扩展exceltk的平台覆盖

**Comment by fanfeilong** [comment]
## Build on Linux (example by ubuntu-x64)
1. install .NET Core SDK 
2. cd to the project dir
3. append the `ubuntu-x64` to following RuntimeIdentifiers in `src/Exceltk/Exceltk.csproj`. you can find other RuntimeIdentifiers at: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
```
  <PropertyGroup>
    <RuntimeIdentifiers>win-x86;osx.10.10-x64;ubuntu-x64</RuntimeIdentifiers>
  </PropertyGroup>
```
4. run the following script step by step.
  - `dotnet restore src/exceltk.sln`
  - `dotnet build src/exceltk.sln` 
  - `dotnet run --project src/Exceltk/Exceltk.csproj -t md -xls src/test/test1.xlsx`

5. run the following script to publish 
```
dotnet publish -r ubuntu-x64 src/exceltk.sln -c Release
```

you can try it.

**Comment by neosun100** [comment]
Thank you for your generous teaching!
